Update README.md
taka292/minia pull request #2
Opened 2024-11-17 02:54 UTC by taka292

### READMEに記載した機能

- [x]  **トップページ**（未ログインでも閲覧可能）
- [x]  レビュー投稿 (画像アップロード機能含む)
- [x]  レビュー一覧（未ログインでも閲覧可能）
- [x]  レビュー詳細（未ログインでも閲覧可能）
- [x]  レビュー更新
- [x]  レビュー削除
- [x]  コメント機能（非 ajax）
- [x]  マイページ
- [x]  投稿履歴
- [x]  欲しいものリスト
- [x]  いいね
- [x]  会員登録 (画像アップロード機能含む)
- [x]  ログイン
- [x]  ログアウト
- [x]  検索機能（未ログインでも閲覧可能）
- [x]  フォロー機能
- [x]  パスワードリセット
- [x]  メールアドレスリセット
- [x]  お問い合わせ
- [x]  利用規約
- [x]  プライバシーポリシー
- [x]  SNS ログイン
- [x]  投稿ポイントシステム（バッジ、ランキング等）
- [x]  レーティング（★評価）

### 未ログインでも閲覧または利用できるページ
以下の項目は適切に未ログインでも閲覧または利用できる画面遷移になっているか？

- [x]  **トップページ**（未ログインでも閲覧可能）
- [x]  レビュー投稿 (画像アップロード機能含む)
- [x]  レビュー一覧（未ログインでも閲覧可能）
- [x]  レビュー詳細（未ログインでも閲覧可能）

### メールアドレス・パスワード変更確認項目
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移になっているか？

- [x]  パスワード
- [x]  メールアドレス

### 各画面の作り込み
画面遷移だけでなく、必要なボタンやフォームが確認できるくらい作り込めているか？ 

- [x]  作り込みはある程度完了している（Figmaを見て画面の作成ができる状態にある）

2024-11-17 02:55 UTC, taka292 commented
### READMEに記載した機能

- [x]  **トップページ**（未ログインでも閲覧可能）
- [x]  レビュー投稿 (画像アップロード機能含む)
- [x]  レビュー一覧（未ログインでも閲覧可能）
- [x]  レビュー詳細（未ログインでも閲覧可能）
- [x]  レビュー更新
- [x]  レビュー削除
- [x]  コメント機能（非 ajax）
- [x]  マイページ
- [x]  投稿履歴
- [x]  欲しいものリスト
- [x]  いいね
- [x]  会員登録 (画像アップロード機能含む)
- [x]  ログイン
- [x]  ログアウト
- [x]  検索機能（未ログインでも閲覧可能）
- [x]  フォロー機能
- [x]  パスワードリセット
- [x]  メールアドレスリセット
- [x]  お問い合わせ
- [x]  利用規約
- [x]  プライバシーポリシー
- [x]  SNS ログイン
- [x]  投稿ポイントシステム（バッジ、ランキング等）
- [x]  レーティング（★評価）

### 未ログインでも閲覧または利用できるページ
以下の項目は適切に未ログインでも閲覧または利用できる画面遷移になっているか？

- [x]  **トップページ**（未ログインでも閲覧可能）
- [x]  レビュー投稿 (画像アップロード機能含む)
- [x]  レビュー一覧（未ログインでも閲覧可能）
- [x]  レビュー詳細（未ログインでも閲覧可能）

### メールアドレス・パスワード変更確認項目
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移になっているか？

- [x]  パスワード
- [x]  メールアドレス

### 各画面の作り込み
画面遷移だけでなく、必要なボタンやフォームが確認できるくらい作り込めているか？ 

- [x]  作り込みはある程度完了している（Figmaを見て画面の作成ができる状態にある）

2024-11-17 05:14 UTC, tarakish requested changes
確認しました👍️
各画面のつながりが分からなかったので、アプリ開発カリキュラムの画面遷移図の課題を参考にフローが分かるように各画面同士を繋いでいただけますか？

2024-11-18 10:49 UTC, taka292 commented
ご確認いただきありがとうございます。
Figmaの画面遷移図で、各画面同士を繋がせていただいたため、
お手数ですがご確認のほどよろしくお願いします。

2024-11-19 01:29 UTC, ippei-shimizu commented
概ね良いかと思います。LGTMです。

2024-11-23 04:28 UTC, merged